### ISSUE TITLE
Tidak Konsisten pada README

### ISSUE THREAD

**Issue by hadihammurabi** [mzaini30/zen-php#1]
Tulisan pertama `Tapi, ini untuk pemakaian offline aja ya. ...`
Kemudian `Tentu karena biaya hosting yang murah ...`

https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang

Lha hosting kan online?

**Comment by mzaini30** [comment]
Oh iya ding. Thanks. Hahahahhaha.

**Comment by hadihammurabi** [comment]
Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`

Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`

Lhaaa ini kan pake internet bosque

**Comment by mzaini30** [comment]
> Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> 
> Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> 
> Lhaaa ini kan pake internet bosque

Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.

Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.

Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.

Jadi mungkin diksinya aku baikin dikit

**Comment by hadihammurabi** [comment]
> > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > Lhaaa ini kan pake internet bosque
> 
> Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> 
> Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> 
> Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> 
> Jadi mungkin diksinya aku baikin dikit

di repo ini ada folder vendornya?

**Comment by mzaini30** [comment]
> > > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > > Lhaaa ini kan pake internet bosque
> > 
> > 
> > Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> > Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> > Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> > Jadi mungkin diksinya aku baikin dikit
> 
> di repo ini ada folder vendornya?

Nggak ada

**Comment by hadihammurabi** [comment]
> > > > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > > > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > > > Lhaaa ini kan pake internet bosque
> > > 
> > > 
> > > Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> > > Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> > > Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> > > Jadi mungkin diksinya aku baikin dikit
> > 
> > 
> > di repo ini ada folder vendornya?
> 
> Nggak ada

berarti untuk bikin folder vendor, download dulu atau enggak?

**Comment by mzaini30** [comment]
> > > > > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > > > > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > > > > Lhaaa ini kan pake internet bosque
> > > > 
> > > > 
> > > > Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> > > > Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> > > > Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> > > > Jadi mungkin diksinya aku baikin dikit
> > > 
> > > 
> > > di repo ini ada folder vendornya?
> > 
> > 
> > Nggak ada
> 
> berarti untuk bikin folder vendor, download dulu atau enggak?

Tapi kan sekali aja downloadnya. Habis tu tinggal copy paste aja.

**Comment by hadihammurabi** [comment]
> > > > > > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > > > > > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > > > > > Lhaaa ini kan pake internet bosque
> > > > > 
> > > > > 
> > > > > Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> > > > > Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> > > > > Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> > > > > Jadi mungkin diksinya aku baikin dikit
> > > > 
> > > > 
> > > > di repo ini ada folder vendornya?
> > > 
> > > 
> > > Nggak ada
> > 
> > 
> > berarti untuk bikin folder vendor, download dulu atau enggak?
> 
> Tapi kan sekali aja downloadnya. Habis tu tinggal copy paste aja.

node_modules di nodejs juga bisa copy paste

**Comment by mzaini30** [comment]
> > > > > > > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > > > > > > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > > > > > > Lhaaa ini kan pake internet bosque
> > > > > > 
> > > > > > 
> > > > > > Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> > > > > > Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> > > > > > Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> > > > > > Jadi mungkin diksinya aku baikin dikit
> > > > > 
> > > > > 
> > > > > di repo ini ada folder vendornya?
> > > > 
> > > > 
> > > > Nggak ada
> > > 
> > > 
> > > berarti untuk bikin folder vendor, download dulu atau enggak?
> > 
> > 
> > Tapi kan sekali aja downloadnya. Habis tu tinggal copy paste aja.
> 
> node_modules di nodejs juga bisa copy paste

Bukannya dia menginstall di root juga ya kalau `npm i`?

**Comment by hadihammurabi** [comment]
> > > > > > > > Tulisan pertama di [Latar Belakang](https://github.com/mzaini30/zen-php/blob/master/README.md#latar-belakang), `Kalau Node JS kan harus pakai internet untuk download package-packagenya.`
> > > > > > > > Lalu pada bagian [Getting Started](https://github.com/mzaini30/zen-php#getting-started) terdapat perintah `composer update`
> > > > > > > > Lhaaa ini kan pake internet bosque
> > > > > > > 
> > > > > > > 
> > > > > > > Kalau di PHP kan, sesudah kita `composer update`, maka akan terbuat folder `vendor`. Nah, kalau sudah ada folder `vendor`, kita nggak perlu `composer update` lagi.
> > > > > > > Berbeda dengan Node JS. Kalau Node JS, kan folder `node_modules`nya nggak bisa kita bawa ke mana-mana tanpa mengupdate repositorinya dengan `npm i`.
> > > > > > > Soalnya kan beberapa paket Node JS memerlukan symlink dengan root. Berbeda dengan PHP yang nggak memerlukan pengait ke root. Jadi, kalau misalnya aku menggunakan Termux di HP, itu bisa saja `composer update` tapi nggak bisa `npm i` karena beberapa paket Node JS memerlukan kaitan ke root.
> > > > > > > Jadi mungkin diksinya aku baikin dikit
> > > > > > 
> > > > > > 
> > > > > > di repo ini ada folder vendornya?
> > > > > 
> > > > > 
> > > > > Nggak ada
> > > > 
> > > > 
> > > > berarti untuk bikin folder vendor, download dulu atau enggak?
> > > 
> > > 
> > > Tapi kan sekali aja downloadnya. Habis tu tinggal copy paste aja.
> > 
> > 
> > node_modules di nodejs juga bisa copy paste
> 
> Bukannya dia menginstall di root juga ya kalau `npm i`?

enggak ada aktivitas di root. coba aja pindahkan node_modules, tetep work kok. jadi sama aja kayak vendor di composer
